In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [38]:

path =  os.path.normpath(os.getcwd() + os.sep + os.pardir)
path.replace('/','\\')
path += '\\'

file = ['Emotion_final_CK_plus_XYZ_NORMAL.csv',
        'Emotion_final_CK_plus_XXX_NORMAL.csv',
        'Emotion_final_CK_plus_SPH_NORMAL.csv',
        'Emotion_final_CK_plus_SPH_NORMAL_XXX.csv',
        'Emotion_final_CK_plus_ANGLE.csv']
    

In [39]:
path = path+file[3]
path

'd:\\majorProjectV2\\Emotion_final_CK_plus_SPH_NORMAL_XXX.csv'

In [40]:
df = pd.read_csv(path)
df = df.drop(['Image_name'], axis = 1)
df = df.drop(['Unnamed: 0'], axis = 1)
for i in range(1,10):
    df = df.sample(frac=1).reset_index(drop=True)
df


0         1         2         3         4         5         6  \
0   -2.154512 -2.016249 -1.877986 -1.739723 -1.601460 -1.238520 -0.961995   
1   -2.098880 -1.956867 -1.814853 -1.672839 -1.530825 -1.246798 -0.891763   
2   -2.234836 -2.093666 -1.970143 -1.828974 -1.634866 -1.299589 -0.964311   
3   -2.096774 -2.029392 -1.962009 -1.877782 -1.743017 -1.456643 -1.170269   
4   -1.898825 -1.829850 -1.760876 -1.691902 -1.553953 -1.278055 -1.002158   
..        ...       ...       ...       ...       ...       ...       ...   
915 -1.888822 -1.821594 -1.670330 -1.603101 -1.468644 -1.250152 -0.964431   
916 -2.249455 -2.181722 -2.113989 -2.046257 -1.910791 -1.639861 -1.233465   
917 -2.071775 -2.004753 -1.937731 -1.853953 -1.719909 -1.451820 -1.166975   
918 -2.028678 -1.977979 -1.842784 -1.775186 -1.572393 -1.318901 -1.048510   
919 -2.017446 -1.950411 -1.816342 -1.749307 -1.548204 -1.280065 -0.944892   

            7         8         9  ...       195       196       197  \
0   -0.547206  0.092260  0.731726  ...  0.347834  0.146081  0.437880   
1   -0.536729  0.102333  0.670389  ...  0.399719  0.174076  0.544255   
2   -0.576096  0.094459  0.623844  ...  0.594174  0.358584  0.679020   
3   -0.749131 -0.176383  0.463748  ...  0.701725  0.499855  0.789723   
4   -0.605555  0.015215  0.635985  ...  0.373388  0.101963  0.535146   
..        ...       ...       ...  ...       ...       ...       ...   
915 -0.611482  0.027188  0.598630  ...  0.009935 -0.223767  0.413920   
916 -0.827069 -0.149742  0.459852  ...  0.518263  0.325725  0.615801   
917 -0.764842 -0.144886  0.475069  ...  0.237402  0.009994  0.566142   
918 -0.659823 -0.000746  0.590735  ...  0.519074  0.319533  0.647646   
919 -0.542685  0.060627  0.663938  ...  0.433696  0.177110  0.588419   

          198       199       200       201       202       203  Emotion  
0    0.481077  0.436469  0.117518  0.443615  0.462322  0.444534        6  
1    0.602238  0.553487  0.175484  0.502477  0.523271  0.492862        6  
2    0.721943  0.665719  0.289732  0.641868  0.671129  0.656840        6  
3    0.826688  0.764569  0.401398  0.716819  0.744466  0.737720        6  
4    0.609705  0.573052  0.196354  0.524122  0.536538  0.485486        6  
..        ...       ...       ...       ...       ...       ...      ...  
915  0.498520  0.439791 -0.183692  0.209498  0.246004  0.181280        5  
916  0.652674  0.588230  0.209918  0.548748  0.578556  0.577411        6  
917  0.623707  0.541561 -0.100189  0.333105  0.392166  0.357757        5  
918  0.681520  0.613085  0.191928  0.576374  0.610816  0.608091        6  
919  0.656865  0.607119  0.211337  0.535991  0.557296  0.515575        6  

[920 rows x 205 columns]

In [41]:
X = []
y = []
y = df.Emotion

In [42]:
df = df.drop(['Emotion'], axis = 1)
df = df*10


In [43]:
X = df.to_numpy()
y = y.to_numpy()

In [44]:
X

array([[-21.54512012, -20.1624912 , -18.77986228, ...,   4.43615127,
          4.62322306,   4.44534256],
       [-20.9888049 , -19.56866686, -18.14852882, ...,   5.02477076,
          5.23270774,   4.92861837],
       [-22.3483565 , -20.93666283, -19.70143086, ...,   6.41867714,
          6.71128746,   6.56839712],
       ...,
       [-20.71775217, -20.04752993, -19.37730769, ...,   3.3310471 ,
          3.92166022,   3.57756608],
       [-20.28677569, -19.77979268, -18.42783801, ...,   5.76373764,
          6.10815769,   6.08090976],
       [-20.17445905, -19.50411299, -18.16342087, ...,   5.35990703,
          5.57296252,   5.15575254]])

In [45]:
fin_y = []
for label in y:
    fin_y.append(np.uint8(label))
y = np.array(fin_y)

In [46]:
np.save('features.npy', X)
np.save('labels.npy', y)

In [47]:
X

array([[-21.54512012, -20.1624912 , -18.77986228, ...,   4.43615127,
          4.62322306,   4.44534256],
       [-20.9888049 , -19.56866686, -18.14852882, ...,   5.02477076,
          5.23270774,   4.92861837],
       [-22.3483565 , -20.93666283, -19.70143086, ...,   6.41867714,
          6.71128746,   6.56839712],
       ...,
       [-20.71775217, -20.04752993, -19.37730769, ...,   3.3310471 ,
          3.92166022,   3.57756608],
       [-20.28677569, -19.77979268, -18.42783801, ...,   5.76373764,
          6.10815769,   6.08090976],
       [-20.17445905, -19.50411299, -18.16342087, ...,   5.35990703,
          5.57296252,   5.15575254]])

In [48]:
y

array([6, 6, 6, 6, 6, 3, 5, 6, 6, 6, 6, 6, 6, 7, 6, 6, 6, 6, 3, 7, 5, 6,
       5, 6, 3, 6, 6, 6, 7, 7, 7, 6, 7, 6, 6, 6, 6, 4, 7, 6, 3, 5, 5, 6,
       6, 6, 1, 6, 5, 3, 7, 6, 6, 6, 1, 6, 3, 6, 6, 6, 6, 6, 6, 6, 2, 1,
       3, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 1, 6, 6, 7, 6, 6, 6, 6,
       4, 6, 4, 6, 6, 6, 6, 6, 6, 1, 6, 6, 6, 6, 6, 6, 3, 6, 6, 4, 6, 6,
       6, 7, 5, 6, 6, 0, 1, 7, 7, 6, 6, 6, 0, 2, 6, 6, 3, 0, 6, 0, 3, 6,
       6, 6, 6, 3, 7, 6, 5, 6, 6, 7, 6, 1, 6, 5, 6, 3, 6, 5, 6, 5, 1, 6,
       6, 6, 6, 5, 6, 2, 6, 5, 6, 6, 6, 6, 6, 6, 4, 6, 6, 6, 6, 6, 1, 5,
       6, 6, 4, 1, 6, 6, 1, 6, 6, 1, 3, 7, 6, 3, 6, 6, 6, 0, 6, 5, 6, 6,
       6, 6, 6, 5, 7, 3, 3, 6, 6, 1, 5, 6, 0, 6, 6, 6, 6, 7, 6, 6, 6, 6,
       5, 0, 6, 6, 6, 6, 3, 4, 6, 6, 6, 6, 6, 6, 0, 5, 7, 6, 6, 6, 1, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 7, 6, 6, 6, 4, 6, 6,
       6, 6, 7, 6, 6, 6, 6, 6, 6, 7, 7, 6, 0, 6, 6, 6, 5, 3, 1, 6, 7, 6,
       6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 5, 6, 5, 7, 6,